twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        user_management: '@App\Service\UserManagement\UserManagement'
        pictures_path: '%pictures_path%'
        pictures_noimage: '%pictures_noimage%'